// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "dev energy",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "dev energy",
            targets: ["AppModule"],
            bundleIdentifier: "jafrin",
            teamIdentifier: "H7YDDV2V7F",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .weights),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "DevQuest uses the camera to detect if you are present at your desk. No video is recorded or saved."),
                .microphone(purposeString: "DevQuest needs microphone access to detect typing intensity (Sonic Sorcery).")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)